services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: todo

  backend:
    depends_on:
      - mongodb
    container_name: express-backend
    ports:
      - 3000:3000
    build:
      context: ./backend
      dockerfile: Dockerfile

  ## uncoment for production purposes
  # frontend:
  #   depends_on:
  #     - backend
  #   container_name: todo-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5173:5173
